Repository octokit/auth-token.js, pull requests merged in 2023-06, with the labels that each got.

#345 fix(build): switch to esbuild and tsc from pika
  package-lock.json
  package.json
  scripts/build.mjs
  src/auth.ts
  src/hook.ts
  src/index.ts
  test/index.test.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#346 build: small fixup follow-up to #345
  package.json
  tsconfig.json
Labels: Type: Maintenance

#340 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Breaking change, Type: Maintenance

#350 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
